<a href="https://colab.research.google.com/github/Ajaysahu01/SWYNEX-Data-Cleaning-Preparation/blob/main/superstore_data_cleaning_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/content/superstore data.csv')
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Region,Sales_Channel,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales_Amount,Cost_Amount,Payment_Method,Order_Status,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,ORD-000001,03/06/2024,CUST-01321,Ananya Joshi,Bhopal,Central,In-store,Bakery,Bread Loaf,1,5.14,0.1,4.63,3.95,Debit Card,completedd,NaN,NaN,NaN
1,ORD-000002,07/18/2025,CUST-01185,Isha Khan,Chennai,South,In-store,Produce,Potatoes 2kg,2,3.2,0.05,6.08,4.74,Credit Card,completedd,NaN,NaN,420.0
2,ORD-000003,04/22/2025,CUST-00189,Ananya Joshi,Mumbai,West,Mobile App,Dairy,Cheese 200g,1,8.39,0,8.39,6.54,UPI,completedd,NaN,NaN,NaN
3,ORD-000004,11/16/2024,CUST-00310,Karan Yadav,Delhi,North,Online,Snacks,Biscuits Pack,4,1.57,0.1,5.65,5.05,Credit Card,completedd,NaN,NaN,NaN
4,ORD-000005,11/12/2024,CUST-01548,Vikram Gupta,Bhopal,Central,Online,Dairy,Paneer 200g,1,2.02,0.2,1.62,1.39,Cash,Returned,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,ORD-011996,08/18/2025,CUST-01053,Vikram Gupta,Kolkata,East,In-store,Dairy,Butter 100g,1,7.61,0,7.61,5.77,UPI,completedd,NaN,NaN,NaN
11996,ORD-011997,02/16/2024,CUST-01016,Karan Yadav,Delhi,North,Mobile App,Produce,Tomatoes 1kg,4,4.24,0,16.96,9.02,Credit Card,Returned,NaN,NaN,NaN
11997,ORD-011998,09/20/2025,CUST-02131,Sneha Singh,Bhopal,Central,Online,Household,Trash Bags,5,17.38,0,86.9,64.45,Cash,completedd,NaN,NaN,NaN
11998,ORD-011999,09/17/2024,CUST-00981,NaN,Hyderabad,South,In-store,Produce,Potatoes 2kg,4,4.79,0,19.16,12.05,UPI,Completed,NaN,NaN,NaN
11999,ORD-012000,08/20/2025,CUST-01605,Pooja Mishra,Jaipur,North,In-store,Bakery,Bread Loaf,8,4.91,0,39.28,26.04,Credit Card,completedd,NaN,NaN,NaN

In [4]:
df.size

228000

In [5]:
df.shape

(12000, 19)

In [6]:
df.isnull().sum()

Order_ID                0
Order_Date             96
Customer_ID             0
Customer_Name         465
City                  363
Region                215
Sales_Channel         180
Product_Category      163
Product_Name          121
Quantity                0
Unit_Price            142
Discount                0
Sales_Amount            0
Cost_Amount             0
Payment_Method        443
Order_Status            0
Unnamed: 16         12000
Unnamed: 17         12000
Unnamed: 18         11999
dtype: int64

In [9]:
df = df.drop(columns=['Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18'])
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Region,Sales_Channel,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales_Amount,Cost_Amount,Payment_Method,Order_Status
0,ORD-000001,03/06/2024,CUST-01321,Ananya Joshi,Bhopal,Central,In-store,Bakery,Bread Loaf,1,5.14,0.1,4.63,3.95,Debit Card,completedd
1,ORD-000002,07/18/2025,CUST-01185,Isha Khan,Chennai,South,In-store,Produce,Potatoes 2kg,2,3.2,0.05,6.08,4.74,Credit Card,completedd
2,ORD-000003,04/22/2025,CUST-00189,Ananya Joshi,Mumbai,West,Mobile App,Dairy,Cheese 200g,1,8.39,0,8.39,6.54,UPI,completedd
3,ORD-000004,11/16/2024,CUST-00310,Karan Yadav,Delhi,North,Online,Snacks,Biscuits Pack,4,1.57,0.1,5.65,5.05,Credit Card,completedd
4,ORD-000005,11/12/2024,CUST-01548,Vikram Gupta,Bhopal,Central,Online,Dairy,Paneer 200g,1,2.02,0.2,1.62,1.39,Cash,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,ORD-011996,08/18/2025,CUST-01053,Vikram Gupta,Kolkata,East,In-store,Dairy,Butter 100g,1,7.61,0,7.61,5.77,UPI,completedd
11996,ORD-011997,02/16/2024,CUST-01016,Karan Yadav,Delhi,North,Mobile App,Produce,Tomatoes 1kg,4,4.24,0,16.96,9.02,Credit Card,Returned
11997,ORD-011998,09/20/2025,CUST-02131,Sneha Singh,Bhopal,Central,Online,Household,Trash Bags,5,17.38,0,86.9,64.45,Cash,completedd
11998,ORD-011999,09/17/2024,CUST-00981,NaN,Hyderabad,South,In-store,Produce,Potatoes 2kg,4,4.79,0,19.16,12.05,UPI,Completed
11999,ORD-012000,08/20/2025,CUST-01605,Pooja Mishra,Jaipur,North,In-store,Bakery,Bread Loaf,8,4.91,0,39.28,26.04,Credit Card,completedd

In [10]:
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Region,Sales_Channel,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales_Amount,Cost_Amount,Payment_Method,Order_Status
0,ORD-000001,03/06/2024,CUST-01321,Ananya Joshi,Bhopal,Central,In-store,Bakery,Bread Loaf,1,5.14,0.1,4.63,3.95,Debit Card,completedd
1,ORD-000002,07/18/2025,CUST-01185,Isha Khan,Chennai,South,In-store,Produce,Potatoes 2kg,2,3.2,0.05,6.08,4.74,Credit Card,completedd
2,ORD-000003,04/22/2025,CUST-00189,Ananya Joshi,Mumbai,West,Mobile App,Dairy,Cheese 200g,1,8.39,0,8.39,6.54,UPI,completedd
3,ORD-000004,11/16/2024,CUST-00310,Karan Yadav,Delhi,North,Online,Snacks,Biscuits Pack,4,1.57,0.1,5.65,5.05,Credit Card,completedd
4,ORD-000005,11/12/2024,CUST-01548,Vikram Gupta,Bhopal,Central,Online,Dairy,Paneer 200g,1,2.02,0.2,1.62,1.39,Cash,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,ORD-011996,08/18/2025,CUST-01053,Vikram Gupta,Kolkata,East,In-store,Dairy,Butter 100g,1,7.61,0,7.61,5.77,UPI,completedd
11996,ORD-011997,02/16/2024,CUST-01016,Karan Yadav,Delhi,North,Mobile App,Produce,Tomatoes 1kg,4,4.24,0,16.96,9.02,Credit Card,Returned
11997,ORD-011998,09/20/2025,CUST-02131,Sneha Singh,Bhopal,Central,Online,Household,Trash Bags,5,17.38,0,86.9,64.45,Cash,completedd
11998,ORD-011999,09/17/2024,CUST-00981,NaN,Hyderabad,South,In-store,Produce,Potatoes 2kg,4,4.79,0,19.16,12.05,UPI,Completed
11999,ORD-012000,08/20/2025,CUST-01605,Pooja Mishra,Jaipur,North,In-store,Bakery,Bread Loaf,8,4.91,0,39.28,26.04,Credit Card,completedd

In [13]:
# Replace placeholder strings with actual NaN values, then drop them
df = df.replace(['ERROR', 'error', 'unknown', 'N/A'], np.nan)
df = df.dropna()
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Region,Sales_Channel,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales_Amount,Cost_Amount,Payment_Method,Order_Status
0,ORD-000001,03/06/2024,CUST-01321,Ananya Joshi,Bhopal,Central,In-store,Bakery,Bread Loaf,1,5.14,0.1,4.63,3.95,Debit Card,completedd
1,ORD-000002,07/18/2025,CUST-01185,Isha Khan,Chennai,South,In-store,Produce,Potatoes 2kg,2,3.2,0.05,6.08,4.74,Credit Card,completedd
2,ORD-000003,04/22/2025,CUST-00189,Ananya Joshi,Mumbai,West,Mobile App,Dairy,Cheese 200g,1,8.39,0,8.39,6.54,UPI,completedd
3,ORD-000004,11/16/2024,CUST-00310,Karan Yadav,Delhi,North,Online,Snacks,Biscuits Pack,4,1.57,0.1,5.65,5.05,Credit Card,completedd
4,ORD-000005,11/12/2024,CUST-01548,Vikram Gupta,Bhopal,Central,Online,Dairy,Paneer 200g,1,2.02,0.2,1.62,1.39,Cash,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11993,ORD-011994,02/27/2025,CUST-00156,Pooja Mishra,Bhopal,Central,In-store,Beverages,Coffee 200g,7,3.28,0,22.96,14.49,Credit Card,Returned
11995,ORD-011996,08/18/2025,CUST-01053,Vikram Gupta,Kolkata,East,In-store,Dairy,Butter 100g,1,7.61,0,7.61,5.77,UPI,completedd
11996,ORD-011997,02/16/2024,CUST-01016,Karan Yadav,Delhi,North,Mobile App,Produce,Tomatoes 1kg,4,4.24,0,16.96,9.02,Credit Card,Returned
11997,ORD-011998,09/20/2025,CUST-02131,Sneha Singh,Bhopal,Central,Online,Household,Trash Bags,5,17.38,0,86.9,64.45,Cash,completedd
11999,ORD-012000,08/20/2025,CUST-01605,Pooja Mishra,Jaipur,North,In-store,Bakery,Bread Loaf,8,4.91,0,39.28,26.04,Credit Card,completedd

In [14]:
df.shape

(9571, 16)

In [15]:
df.columns = df.columns.str.strip()

In [16]:
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Region,Sales_Channel,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales_Amount,Cost_Amount,Payment_Method,Order_Status
0,ORD-000001,03/06/2024,CUST-01321,Ananya Joshi,Bhopal,Central,In-store,Bakery,Bread Loaf,1,5.14,0.1,4.63,3.95,Debit Card,completedd
1,ORD-000002,07/18/2025,CUST-01185,Isha Khan,Chennai,South,In-store,Produce,Potatoes 2kg,2,3.2,0.05,6.08,4.74,Credit Card,completedd
2,ORD-000003,04/22/2025,CUST-00189,Ananya Joshi,Mumbai,West,Mobile App,Dairy,Cheese 200g,1,8.39,0,8.39,6.54,UPI,completedd
3,ORD-000004,11/16/2024,CUST-00310,Karan Yadav,Delhi,North,Online,Snacks,Biscuits Pack,4,1.57,0.1,5.65,5.05,Credit Card,completedd
4,ORD-000005,11/12/2024,CUST-01548,Vikram Gupta,Bhopal,Central,Online,Dairy,Paneer 200g,1,2.02,0.2,1.62,1.39,Cash,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11993,ORD-011994,02/27/2025,CUST-00156,Pooja Mishra,Bhopal,Central,In-store,Beverages,Coffee 200g,7,3.28,0,22.96,14.49,Credit Card,Returned
11995,ORD-011996,08/18/2025,CUST-01053,Vikram Gupta,Kolkata,East,In-store,Dairy,Butter 100g,1,7.61,0,7.61,5.77,UPI,completedd
11996,ORD-011997,02/16/2024,CUST-01016,Karan Yadav,Delhi,North,Mobile App,Produce,Tomatoes 1kg,4,4.24,0,16.96,9.02,Credit Card,Returned
11997,ORD-011998,09/20/2025,CUST-02131,Sneha Singh,Bhopal,Central,Online,Household,Trash Bags,5,17.38,0,86.9,64.45,Cash,completedd
11999,ORD-012000,08/20/2025,CUST-01605,Pooja Mishra,Jaipur,North,In-store,Bakery,Bread Loaf,8,4.91,0,39.28,26.04,Credit Card,completedd

In [17]:
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Region,Sales_Channel,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales_Amount,Cost_Amount,Payment_Method,Order_Status
0,ORD-000001,03/06/2024,CUST-01321,Ananya Joshi,Bhopal,Central,In-store,Bakery,Bread Loaf,1,5.14,0.1,4.63,3.95,Debit Card,completedd
1,ORD-000002,07/18/2025,CUST-01185,Isha Khan,Chennai,South,In-store,Produce,Potatoes 2kg,2,3.2,0.05,6.08,4.74,Credit Card,completedd
2,ORD-000003,04/22/2025,CUST-00189,Ananya Joshi,Mumbai,West,Mobile App,Dairy,Cheese 200g,1,8.39,0,8.39,6.54,UPI,completedd
3,ORD-000004,11/16/2024,CUST-00310,Karan Yadav,Delhi,North,Online,Snacks,Biscuits Pack,4,1.57,0.1,5.65,5.05,Credit Card,completedd
4,ORD-000005,11/12/2024,CUST-01548,Vikram Gupta,Bhopal,Central,Online,Dairy,Paneer 200g,1,2.02,0.2,1.62,1.39,Cash,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11993,ORD-011994,02/27/2025,CUST-00156,Pooja Mishra,Bhopal,Central,In-store,Beverages,Coffee 200g,7,3.28,0,22.96,14.49,Credit Card,Returned
11995,ORD-011996,08/18/2025,CUST-01053,Vikram Gupta,Kolkata,East,In-store,Dairy,Butter 100g,1,7.61,0,7.61,5.77,UPI,completedd
11996,ORD-011997,02/16/2024,CUST-01016,Karan Yadav,Delhi,North,Mobile App,Produce,Tomatoes 1kg,4,4.24,0,16.96,9.02,Credit Card,Returned
11997,ORD-011998,09/20/2025,CUST-02131,Sneha Singh,Bhopal,Central,Online,Household,Trash Bags,5,17.38,0,86.9,64.45,Cash,completedd
11999,ORD-012000,08/20/2025,CUST-01605,Pooja Mishra,Jaipur,North,In-store,Bakery,Bread Loaf,8,4.91,0,39.28,26.04,Credit Card,completedd

In [18]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
City                0
Region              0
Sales_Channel       0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount            0
Sales_Amount        0
Cost_Amount         0
Payment_Method      0
Order_Status        0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(47)

In [20]:
df = df.drop_duplicates()

In [21]:
print("Rows and Columns:", df.shape)
print("Duplicate Rows:", df.duplicated().sum())

Rows and Columns: (9524, 16)
Duplicate Rows: 0

In [30]:
df.dtypes

Order_ID            object
Order_Date          object
Customer_ID         object
Customer_Name       object
City                object
Region              object
Sales_Channel       object
Product_Category    object
Product_Name        object
Quantity            object
Unit_Price          object
Discount            object
Sales_Amount        object
Cost_Amount         object
Payment_Method      object
Order_Status        object
dtype: object

In [26]:
df.select_dtypes(include='object').head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Region,Sales_Channel,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales_Amount,Cost_Amount,Payment_Method,Order_Status
0,ORD-000001,03/06/2024,CUST-01321,Ananya Joshi,Bhopal,Central,In-store,Bakery,Bread Loaf,1,5.14,0.1,4.63,3.95,Debit Card,completedd
1,ORD-000002,07/18/2025,CUST-01185,Isha Khan,Chennai,South,In-store,Produce,Potatoes 2kg,2,3.2,0.05,6.08,4.74,Credit Card,completedd
2,ORD-000003,04/22/2025,CUST-00189,Ananya Joshi,Mumbai,West,Mobile App,Dairy,Cheese 200g,1,8.39,0,8.39,6.54,UPI,completedd
3,ORD-000004,11/16/2024,CUST-00310,Karan Yadav,Delhi,North,Online,Snacks,Biscuits Pack,4,1.57,0.1,5.65,5.05,Credit Card,completedd
4,ORD-000005,11/12/2024,CUST-01548,Vikram Gupta,Bhopal,Central,Online,Dairy,Paneer 200g,1,2.02,0.2,1.62,1.39,Cash,Returned

In [42]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed').dt.strftime('%d-%m-%y')
df.head()

/tmp/ipykernel_1377/1731218793.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed').dt.strftime('%d-%m-%y')

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Region,Sales_Channel,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales_Amount,Cost_Amount,Payment_Method,Order_Status
0,ORD-000001,03-06-24,CUST-01321,Ananya Joshi,Bhopal,Central,In-store,Bakery,Bread Loaf,1,5.14,0.1,4.63,3.95,Debit Card,completedd
1,ORD-000002,18-07-25,CUST-01185,Isha Khan,Chennai,South,In-store,Produce,Potatoes 2kg,2,3.2,0.05,6.08,4.74,Credit Card,completedd
2,ORD-000003,22-04-25,CUST-00189,Ananya Joshi,Mumbai,West,Mobile App,Dairy,Cheese 200g,1,8.39,0,8.39,6.54,UPI,completedd
3,ORD-000004,16-11-24,CUST-00310,Karan Yadav,Delhi,North,Online,Snacks,Biscuits Pack,4,1.57,0.1,5.65,5.05,Credit Card,completedd
4,ORD-000005,11-12-24,CUST-01548,Vikram Gupta,Bhopal,Central,Online,Dairy,Paneer 200g,1,2.02,0.2,1.62,1.39,Cash,Returned

In [36]:
df[['Order_Date']]

      Order_Date
0       06-03-24
1       18-07-25
2       22-04-25
3       16-11-24
4       12-11-24
...          ...
11993   27-02-25
11995   18-08-25
11996   16-02-24
11997   20-09-25
11999   20-08-25

[9524 rows x 1 columns]

In [39]:
df.describe(include="all")

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Region,Sales_Channel,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales_Amount,Cost_Amount,Payment_Method,Order_Status
count,9524,9524,9524,9524,9524,9524,9524,9524,9524,9524,9524,9524,9524,9524,9524,9524
unique,9524,730,2533,13,16,5,6,9,30,12,1860,5,4646,4230,5,7
top,ORD-012000,07-08-25,CUST-01628,Karan Yadav,Ahmedabad,West,In-store,Produce,Potatoes 2kg,1,3.23,0,16.32,6.11,UPI,completedd
freq,1,25,11,830,667,1959,4868,2032,430,1209,20,4764,13,11,2613,8563

In [45]:
numeric_cols = ['Quantity', 'Unit_Price', 'Discount', 'Sales_Amount', 'Cost_Amount']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Now describe the numeric columns
df.describe(include='number')

/tmp/ipykernel_1377/2695745423.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors='coerce')

          Quantity   Unit_Price     Discount  Sales_Amount  Cost_Amount
count  9524.000000  9524.000000  9524.000000   9524.000000  9524.000000
mean      4.661697    21.461772     0.052635     28.958027    20.494095
std       5.201091   382.873440     0.062344     27.749432    19.859718
min      -3.000000    -5.000000     0.000000      0.640000     0.420000
25%       2.000000     3.267500     0.000000      9.490000     6.685000
50%       4.000000     5.640000     0.000000     20.480000    14.490000
75%       7.000000     8.570000     0.100000     38.645000    27.140000
max     150.000000  9999.000000     0.200000    199.120000   156.940000

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9524 entries, 0 to 11999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          9524 non-null   object
 1   Order_Date        9524 non-null   object
 2   Customer_ID       9524 non-null   object
 3   Customer_Name     9524 non-null   object
 4   City              9524 non-null   object
 5   Region            9524 non-null   object
 6   Sales_Channel     9524 non-null   object
 7   Product_Category  9524 non-null   object
 8   Product_Name      9524 non-null   object
 9   Quantity          9524 non-null   int64
 10  Unit_Price        9524 non-null   float64
 11  Discount          9524 non-null   float64
 12  Sales_Amount      9524 non-null   float64
 13  Cost_Amount       9524 non-null   float64
 14  Payment_Method    9524 non-null   object
 15  Order_Status      9524 non-null   object
dtypes: float64(4), int64(1), object(11)
memory usage: 1.5+ MB

In [46]:
df.to_excel('Superstore_Cleaned.xlsx', index=False)

In [47]:
from google.colab import files
files.download('Superstore_Cleaned.xlsx')